---
title: "Exploration"
author: "Sebastian Kirkpatrick"
date: "2024-01-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
library("viridis")
```

```{r}
szn <- read_csv("fangraphs_season_level.csv")

pitches <- read_csv("savant_pitch_level.csv")
```

```{r}
head(pitches)
head(szn)
```

```{r}
pitches |>
  filter(player_name == "Burnes, Corbin" & game_year == 2021) |>
  filter(pitch_type == "FC") |>
  ggplot(
    aes(x=pitch_number_appearance, y=release_spin_rate)
  ) + geom_line(aes(group=game_date)) + geom_smooth(method = "loess", se = FALSE)
```

```{r}
pitches |>
  filter(player_name == "Ray, Robbie" & game_year == 2021) |>
  filter(pitch_type == "FF") |>
  ggplot(
    aes(x=pitch_number_appearance, y=release_spin_rate)
  ) + geom_line(aes(group=game_date)) + geom_smooth(method = "loess", se = FALSE)
```

```{r}
pitches |>
  filter(player_name == "Hader, Josh" & game_year == 2021) |>
  filter(pitch_type == "SI") |>
  ggplot(
    aes(x=pitch_number_appearance, y=release_spin_rate)
  ) + geom_line(aes(group=game_date)) + geom_smooth(method = "loess", se = FALSE)
```

```{r}
pitches |>
  filter(player_name == "Hendriks, Liam" & game_year == 2021) |>
    filter(pitch_type == "FF") |>
  ggplot(
    aes(x=pitch_number_appearance, y=release_spin_rate)
  ) + geom_line(aes(group=game_date)) + geom_smooth(method = "loess", se = FALSE)
```

```{r}
#Fastball
szn |>
  select(c(4, 5, 6, 9, 12, 285:287)) |>
  filter(IP > 45) |>
  group_by(Role) |>
  summarize(med_Stf = median(Stf_plus_FA, na.rm=TRUE), med_Loc = median(Loc_plus_FA, na.rm=TRUE), med_Pit = median(Pit_plus_FA, na.rm=TRUE))
```

```{r}
#Pitch Percentages

pp <- szn |>
  filter(IP > 45 & xFIP_minus < 85) |>
  select(4, 6, 9, 12, 99, 170:172, 174:177, 179, 180) |>
  rename(
    "Fastball" = 6, 
    "Cutter" = 7, 
    "Split_Finger" = 8, 
    "Sinker" = 9, 
    "Slider" = 10, 
    "Curveball" = 11, 
    "Knuckle_Curve" = 12, 
    "Changeup" = 13, 
    "Screwball" = 14
    )

```

```{r}
pp2 <- pp |>
  replace(is.na(pp),0) |>
  mutate("Primary" = 
           pmax(Fastball,Cutter,Split_Finger,Sinker,Slider,Curveball,Knuckle_Curve,Changeup,Screwball)) |>
  mutate("Secondary" = 
           apply(
             pp[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               second <- values_sorted[2]
               return(second)
             }
           )
  ) |> 
  mutate("Third" = 
           apply(
             pp[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               third <- values_sorted[3]
               return(third)
             }
           )
  ) |> 
  mutate("Fourth" = 
           apply(
             pp[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               fourth <- values_sorted[4]
               return(fourth)
             }
           )
  ) |> 
  mutate("Fifth" = 
           apply(
             pp[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               fifth <- values_sorted[5]
               return(fifth)
             }
           )
  )
```

```{r}
pp2 |>
  replace(is.na(pp2),0) |>
  group_by(Role) |>
  summarize(median(Third))
```

```{r}
pp3 <- pp2 |>
  replace(is.na(pp2),0)
```


```{r}
pp3 |>
  ggplot(
  aes(x=Third, y=-xFIP_minus, color=Role)
) + geom_point() + geom_smooth(method="loess",se=F)
```

```{r}
# PitchingBot Pitch Grades

pg <- szn |>
  filter(ifelse(Role == "SP", G > 15, G > 30)) |>
  select(4, 6, 9, 251, 254, 257, 260, 263, 266, 269, 272, 99) |>
  rename(
    "Changeup" = 4, 
    "Curveball" = 5, 
    "Fastball" = 6, 
    "Sinker" = 7, 
    "Slider" = 8, 
    "Knuckle_Curve" = 9, 
    "Cutter" = 10, 
    "Split_Finger" = 11
    ) |>
  pivot_longer(cols=c("Changeup", "Curveball", "Fastball", "Sinker", "Slider", "Knuckle_Curve", "Cutter", "Split_Finger"), names_to = "Pitch", values_to = "Grade") |>
  drop_na()
```

```{r}
pg2 <- pg |> 
  filter(Grade > 55) |>
  group_by(NameASCII, Role, Season, xFIP_minus) |>
  summarize(Num50 = n()) |>
  mutate(xFIP_dummy = xFIP_minus < 100)
```

```{r}
pg2 |>
  group_by(Role, Num50, xFIP_dummy) |>
  summarize(Count = n()) |>
  ggplot(
    aes(x=Num50, y=Count, fill = Role)
  ) + geom_bar(stat = "identity") + facet_wrap(~ xFIP_dummy)
```

```{r}
#Clustering

dist <- szn |>
  mutate(P_per_G = Pitches/G) |>
  select(P_per_G, G) |>
  scale(center = FALSE, scale = TRUE) |>
  dist()
```

```{r}
obj <- hclust(dist)
plot(hclust(dist))
```

```{r}
szn |>
  mutate(cluster = cutree(obj,k=6), 
         P_per_G = Pitches/G,
         Full_IP = trunc(IP),
         Partial_Outs = 10 * (IP - trunc(IP)),
         Outs = 3 * Full_IP + Partial_Outs,
         O_per_G = Outs/G) |>
  select(cluster,P_per_G,O_per_G,G) |>
  group_by(cluster) |>
  summarize(mean(G), mean(P_per_G), mean(O_per_G), n())
```

```{r}
szn |>
  mutate(cluster = cutree(obj,k=5), P_per_G = Pitches/G) |>
  select(NameASCII, IP, G, P_per_G, cluster) |>
  filter(NameASCII == "Ian Gibaut")
```

```{r}
ss <- function(x) {
  filtered <- szn |>
  mutate(cluster = cutree(obj,k=x), P_per_G = Pitches/G)
  average <- filtered |>
    select(cluster,P_per_G,G) |>
    group_by(cluster) |>
    summarize(cluster_mean = mean(P_per_G), cluster_G = mean(G))
  left_join(filtered, average, by = "cluster") |>
    mutate(ss = (cluster_mean - P_per_G)(cluster_G - mean(G))) |>
    select(Name, P_per_G, cluster, cluster_mean, ss) |>
    summarize(sum(ss))
}
```

```{r}
k_clusters <- as.numeric(C(1:10))

results <- lapply(k_clusters, ss)

sss <- data.frame(k_clusters, sum_of_squares = unlist(results))
```

```{r}
ggplot(data = sss,
  aes(x=k_clusters, y=sum_of_squares)
) + geom_point() + geom_line() + scale_x_continuous(breaks = (1:10))
```

```{r}
szn |>
  filter(ifelse(Role == "SP", GS > 15, IP > 50)) |>
  select(Role,IP) |>
  group_by(Role) |>
  summarize(count = n())
```

```{r}
dat <- szn |>
  select_if(~!is.logical(.)) |>
  mutate(P_per_G = Pitches/G,
         Full_IP = trunc(IP),
         Partial_Outs = IP - trunc(IP),
         Outs = 3 * Full_IP + 10 * Partial_Outs,
         O_per_G = Outs/G, 
         Innings = Outs/3)
```

```{r}
tree <- dat |>
  select(G, P_per_G, O_per_G, Innings) |>
  scale(center = T, scale = T) |>
  dist(method = "euclidean") |>
  hclust(method="ward.D2")
```

```{r}
plot(tree)
```

```{r}
clust <- dat |>
  select(G, P_per_G, O_per_G, Innings) |>
  scale(center = T, scale = T) |>
  data.frame() |>
  mutate(cluster = cutree(tree,k=5))


clust_means <- clust |>
  group_by(cluster) |>
  summarize(clust_G = mean(G), 
            clust_P_per_G = mean(P_per_G), 
            clust_O_per_G = mean(O_per_G), 
            clust_Innings = mean(Innings))
  
  
left_join(clust, clust_means, by = "cluster")|>
  mutate(ss = (clust_G - G)^2 + (clust_P_per_G - P_per_G)^2 + (clust_O_per_G - O_per_G)^2 + (clust_Innings - Innings)^2 ) |>
  summarize(sum(ss))

sum_s(5)
```

```{r}
sum_s <- function(x) {
  clust <- dat |>
    select(P_per_G, O_per_G, Innings) |>
    scale(center = T, scale = T) |>
    data.frame() |>
    mutate(cluster = cutree(tree,k=x))
  clust_means <- clust |>
    group_by(cluster) |>
    summarize(clust_P_per_G = mean(P_per_G), 
              clust_O_per_G = mean(O_per_G), 
              clust_Innings = mean(Innings))
  left_join(clust, clust_means, by = "cluster") |>
    mutate(ss = (clust_P_per_G - P_per_G)^2 + (clust_O_per_G - O_per_G)^2 + (clust_Innings - Innings)^2 ) |>
    summarize(sum(ss))
}
```

```{r}
k_clusters <- as.numeric(C(1:10))

results <- lapply(k_clusters, sum_s)

sss <- data.frame(k_clusters, sum_of_squares = unlist(results))
```

```{r}
ggplot(data=sss,
  aes(x=k_clusters, y=sum_of_squares) 
) + geom_point() + geom_line() + scale_x_continuous(breaks = (1:10))
```

```{r}
dat |>
  select(NameASCII, G, P_per_G, O_per_G, Innings) |>
  mutate(cluster = cutree(tree,k=4)) |>
  group_by(cluster) |>
  summarize(mean_G = mean(G), mean_P = mean(P_per_G), mean_O = mean(O_per_G), mean_I = mean(Innings))
```

```{r}
dat|>
  select(NameASCII, Role, G, P_per_G, O_per_G, Innings) |>
  mutate(cluster = cutree(tree,k=7)) |>
  filter(cluster == 3)
```

```{r}
plot(tree)

dat_clust <- dat |>
  mutate(cluster = cutree(tree,k=10))
```

```{r}
starter <- dat |>
  filter(Role == "SP", GS > 10)
```

```{r}
ggplot(data=starter,
  aes(x=ERA, y = WPA, color=Innings)
) + geom_point() + scale_color_viridis_c(option = "turbo")
```

```{r}
ggplot(data=starter,
  aes(x=xFIP_minus, y = ERA_minus, color=Innings)
) + geom_point() + scale_color_viridis_c(option = "turbo")
```

```{r}
num_starter <- starter |>
  select(is.numeric)

which.max(cor(num_starter$ERA, num_starter))
num_starter[19]
```

```{r}
dat <- szn |>
  filter(IP > 30 & G > 15) |>
  select_if(~!is.logical(.)) |>
  mutate(P_per_G = Pitches/G,
         Full_IP = trunc(IP),
         Partial_Outs = IP - trunc(IP),
         Outs = 3 * Full_IP + 10 * Partial_Outs,
         O_per_G = Outs/G, 
         Innings = Outs/3)
```

```{r}
tree <- dat |>
  select(O_per_G, gmLI) |>
  scale(center = T, scale = T) |>
  dist(method = "euclidean") |>
  hclust(method="complete")
```

```{r}
plot(tree) + abline(h=2.2, col="red")
```

```{r}
dat |>
  select(NameASCII, G, P_per_G, O_per_G, Innings, gmLI) |>
  mutate(cluster = cutree(tree,k=5)) |>
  group_by(cluster) |>
  summarize(mean_G = mean(G), mean_P = mean(P_per_G), mean_O = mean(O_per_G), mean_I = mean(Innings), mean_gmLI = mean(gmLI), count = n())
```

```{r}
dat|>
  select(NameASCII, Season, Role, SV, P_per_G, O_per_G, Innings, gmLI) |>
  mutate(cluster = cutree(tree,k=5)) |>
  filter(cluster == 4)
```


```{r}
szn_pitch <- szn |>
  replace(is.na(szn),0) |>
  filter(Role == "SP", G > 15) |>
  select(4, 6, 9, 12, 97, 170:172, 174:177, 179, 180) |>
  rename(
    "Fastball" = 6, 
    "Cutter" = 7, 
    "Split_Finger" = 8, 
    "Sinker" = 9, 
    "Slider" = 10, 
    "Curveball" = 11, 
    "Knuckle_Curve" = 12, 
    "Changeup" = 13, 
    "Screwball" = 14
    )

arsenal_p <- szn_pitch |>
  mutate("Primary" = 
           pmax(Fastball,Cutter,Split_Finger,Sinker,Slider,Curveball,Knuckle_Curve,Changeup,Screwball)) |>
  mutate("Secondary" = 
           apply(
             szn_pitch[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               second <- values_sorted[2]
               return(second)
             }
           )
  ) |> 
  mutate("Third" = 
           apply(
             szn_pitch[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               third <- values_sorted[3]
               return(third)
             }
           )
  ) |> 
  mutate("Fourth" = 
           apply(
             szn_pitch[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               fourth <- values_sorted[4]
               return(fourth)
             }
           )
  ) |> 
  mutate("Fifth" = 
           apply(
             szn_pitch[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               fifth <- values_sorted[5]
               return(fifth)
             }
           )
  )
```
  
```{r}
cor(arsenal_p$ERA_minus, arsenal_p[15:19])
```
  
```{r}
mod <- lm(ERA_minus ~ Third, data = arsenal_p)
plot(mod)
summary(mod)
```

```{r}
szn_pitch <- szn |>
  replace(is.na(szn),0) |>
  filter(Role == "SP", G > 15) |>
  select(4, 6, 9, 12, 97, 279, 282, 285, 288, 291, 294, 297, 300, 304) |>
  rename(
    "Changeup" = 6, 
    "Curveball" = 7, 
    "Fastball" = 8, 
    "Sinker" = 9, 
    "Slider" = 10, 
    "Knuckle_Curve" = 11, 
    "Cutter" = 12, 
    "Split_Finger" = 13, 
    "Forkball" = 14
    )

arsenal_stf <- szn_pitch |>
  mutate("Primary" = 
           pmax(Changeup,Curveball,Fastball,Sinker,Slider,Knuckle_Curve,Cutter,Split_Finger,Forkball)) |>
  mutate("Secondary" = 
           apply(
             szn_pitch[,c("Changeup","Curveball","Fastball","Sinker","Slider","Knuckle_Curve","Cutter","Split_Finger","Forkball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               second <- values_sorted[2]
               return(second)
             }
           )
  ) |> 
  mutate("Third" = 
           apply(
            szn_pitch[,c("Changeup","Curveball","Fastball","Sinker","Slider","Knuckle_Curve","Cutter","Split_Finger","Forkball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               third <- values_sorted[3]
               return(third)
             }
           )
  ) |> 
  mutate("Fourth" = 
           apply(
             szn_pitch[,c("Changeup","Curveball","Fastball","Sinker","Slider","Knuckle_Curve","Cutter","Split_Finger","Forkball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               fourth <- values_sorted[4]
               return(fourth)
             }
           )
  ) |> 
  mutate("Fifth" = 
           apply(
             szn_pitch[,c("Changeup","Curveball","Fastball","Sinker","Slider","Knuckle_Curve","Cutter","Split_Finger","Forkball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               fifth <- values_sorted[5]
               return(fifth)
             }
           )
  )
```

```{r}
cor(arsenal_stf$ERA_minus, arsenal_stf[15:19])
```

```{r}
mod <- lm(ERA_minus ~ Primary + Secondary + Third + Fourth + Fifth, data = arsenal_stf)
plot(mod)
summary(mod)

plot(fitted(mod))
plot(mod)
```

```{r}
szn_pitch_rp <- szn |>
  replace(is.na(szn),0) |>
  filter(Role == "RP", IP > 25) |>
  select(4, 6, 9, 12, 97, 170:172, 174:177, 179, 180) |>
  rename(
    "Fastball" = 6, 
    "Cutter" = 7, 
    "Split_Finger" = 8, 
    "Sinker" = 9, 
    "Slider" = 10, 
    "Curveball" = 11, 
    "Knuckle_Curve" = 12, 
    "Changeup" = 13, 
    "Screwball" = 14
    )

arsenal_p_rp <- szn_pitch_rp |>
  mutate("Primary" = 
           pmax(Fastball,Cutter,Split_Finger,Sinker,Slider,Curveball,Knuckle_Curve,Changeup,Screwball)) |>
  mutate("Secondary" = 
           apply(
             szn_pitch_rp[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               second <- values_sorted[2]
               return(second)
             }
           )
  ) |> 
  mutate("Third" = 
           apply(
             szn_pitch_rp[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               third <- values_sorted[3]
               return(third)
             }
           )
  ) |> 
  mutate("Fourth" = 
           apply(
             szn_pitch_rp[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               fourth <- values_sorted[4]
               return(fourth)
             }
           )
  ) |> 
  mutate("Fifth" = 
           apply(
             szn_pitch_rp[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               fifth <- values_sorted[5]
               return(fifth)
             }
           )
  )
```
  
```{r}
cor(arsenal_p_rp$ERA_minus, arsenal_p_rp[15:19])
```

```{r}
szn_pitch_rp <- szn |>
  replace(is.na(szn),0) |>
  filter(Role == "RP", IP > 25) |>
  select(4, 6, 9, 12, 97, 279, 282, 285, 288, 291, 294, 297, 300, 304) |>
  rename(
    "Changeup" = 6, 
    "Curveball" = 7, 
    "Fastball" = 8, 
    "Sinker" = 9, 
    "Slider" = 10, 
    "Knuckle_Curve" = 11, 
    "Cutter" = 12, 
    "Split_Finger" = 13, 
    "Forkball" = 14
    )

arsenal_stf_rp <- szn_pitch_rp |>
  mutate("Primary" = 
           pmax(Changeup,Curveball,Fastball,Sinker,Slider,Knuckle_Curve,Cutter,Split_Finger,Forkball)) |>
  mutate("Secondary" = 
           apply(
             szn_pitch_rp[,c("Changeup","Curveball","Fastball","Sinker","Slider","Knuckle_Curve","Cutter","Split_Finger","Forkball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               second <- values_sorted[2]
               return(second)
             }
           )
  ) |> 
  mutate("Third" = 
           apply(
            szn_pitch_rp[,c("Changeup","Curveball","Fastball","Sinker","Slider","Knuckle_Curve","Cutter","Split_Finger","Forkball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               third <- values_sorted[3]
               return(third)
             }
           )
  ) |> 
  mutate("Fourth" = 
           apply(
             szn_pitch_rp[,c("Changeup","Curveball","Fastball","Sinker","Slider","Knuckle_Curve","Cutter","Split_Finger","Forkball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               fourth <- values_sorted[4]
               return(fourth)
             }
           )
  ) |> 
  mutate("Fifth" = 
           apply(
             szn_pitch_rp[,c("Changeup","Curveball","Fastball","Sinker","Slider","Knuckle_Curve","Cutter","Split_Finger","Forkball")], 1, function(x) {
               values_sorted <- sort(x, decreasing=T)
               fifth <- values_sorted[5]
               return(fifth)
             }
           )
  )
```

```{r}
cor(arsenal_stf_rp$ERA_minus, arsenal_stf_rp[15:19])
```

```{r}
sa1 |>
  filter(NameASCII == "Adam Ottavino")
```


```{r}
szn_arsenal <- szn |>
  replace(is.na(szn),0) |>
  filter(Role == "SP", IP > 100) |>
  select(4, 6, 9, 12, 97, 170:172, 174:177, 179, 180) |>
  rename(
    "Fastball" = 6, 
    "Cutter" = 7, 
    "Split_Finger" = 8, 
    "Sinker" = 9, 
    "Slider" = 10, 
    "Curveball" = 11, 
    "Knuckle_Curve" = 12, 
    "Changeup" = 13,
    "Screwball" = 14
    )

sa1 <- szn_arsenal |>
  mutate("Primary" = apply(szn_arsenal[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) names(x)[order(x, decreasing = T)[1]])) |>
  mutate("Secondary" = apply(szn_arsenal[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) names(x)[order(x, decreasing = T)[2]])) |>
  mutate("Third" = apply(szn_arsenal[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) names(x)[order(x, decreasing = T)[3]])) |>
  mutate("Fourth" = apply(szn_arsenal[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) names(x)[order(x, decreasing = T)[4]])) |>
  mutate("Fifth" = apply(szn_arsenal[,c("Fastball","Cutter","Split_Finger","Sinker","Slider","Curveball","Knuckle_Curve","Changeup","Screwball")], 1, function(x) names(x)[order(x, decreasing = T)[5]])) |>
  select(1,2,3,5,15:19) |>
  pivot_longer(cols=c(5:9), names_to = "Arsenal", values_to = "Pitch")
```

```{r}
sa2 <- szn |>
  replace(is.na(szn),0) |>
  filter(Role == "SP", IP > 100) |>
  select(4, 6, 9, 12, 97, 279, 282, 285, 288, 291, 294, 297, 300, 304) |>
  rename(
    "Changeup" = 6, 
    "Curveball" = 7, 
    "Fastball" = 8, 
    "Sinker" = 9, 
    "Slider" = 10, 
    "Knuckle_Curve" = 11, 
    "Cutter" = 12, 
    "Split_Finger" = 13, 
    "Forkball" = 14
    ) |> 
  select(1,2,3,5:14) |>
  pivot_longer(cols = c(5:13), names_to = "Pitch", values_to = "Stuff_plus")
```

```{r}
arsenal_grades <- left_join(sa1, sa2, by = c("NameASCII", "Season", "Role", "ERA_minus", "Pitch")) |>
  select(!6) |>
  pivot_wider(names_from = "Arsenal", values_from = "Stuff_plus")
```

```{r}
cor(arsenal_grades$ERA_minus, arsenal_grades[5:9], use = "complete.obs")
```

```{r}
cor(rp_grade$ERA_minus, rp_grade[4:8], use = "complete.obs")
```

```{r}
mod_sp <- lm(ERA_minus ~ Primary + Secondary, data=sp_grade)
summary(mod_sp)
```

```{r}
mod_rp <- lm(ERA_minus ~ Primary + Secondary, data=rp_grade)
summary(mod_rp)
```

```{r}
head(pitches)
pitches |>
  filter(times_faced == 4, role_key == "RP")
```


```{r}
duration <- pitches |>
  select(player_name, woba_value, role_key, pitch_number_appearance, pitcher_at_bat_number, times_faced) |>
  filter(!is.na(woba_value)) |>
  group_by(role_key, pitch_number_appearance) |>
  summarize(mean_woba = mean(woba_value), count = n())
```

```{r}
duration |>
  ggplot(
    aes(x=pitch_number_appearance, y=mean_woba, color=role_key)
  ) + geom_smooth(method = "loess", se=F)
```

```{r}
results <- pitches |>
  filter(pitch_type == "FF") |>
  group_by(pitch_type, game_date, player_name, role_key, pitcher_at_bat_number) |>
  summarize(mean_velo = mean(release_speed)) |>
  pivot_wider(names_from = pitcher_at_bat_number, names_sort = T, values_from = mean_velo) |>
  mutate(across(starts_with("2") : ends_with("35"), ~ . - `1`, .names = "{.col}")) |>
  group_by(player_name, role_key) |>
  summarize(across(c(4:37), mean, na.rm = TRUE)) |>
  pivot_longer(cols = c(3:36), names_to = "Pitch", values_to = "Difference") |>
  mutate(Pitch = as.numeric(Pitch)) |> 
  na.omit()
```

```{r}
ggplot(data=results,
       aes(x=Pitch, y=Difference)
  ) + geom_point() + geom_smooth(method = "lm", se=F) + facet_wrap(~role_key) +
  labs(title = "Four-Seam Fastball Velocity Average Difference", x="At-Bat", y="Difference in Velo from First Pitch")
```

```{r}
results_cu <- pitches |>
  filter(pitch_type == "FC") |>
  group_by(pitch_type, game_date, player_name, role_key, pitcher_at_bat_number) |>
  summarize(mean_velo = mean(release_speed)) |>
  pivot_wider(names_from = pitcher_at_bat_number, names_sort = T, values_from = mean_velo) |>
  mutate(across(starts_with("2") : ends_with("35"), ~ . - `1`, .names = "{.col}")) |>
  group_by(player_name, role_key) |>
  summarize(across(c(4:37), mean, na.rm = TRUE)) |>
  pivot_longer(cols = c(3:36), names_to = "Pitch", values_to = "Difference") |>
  mutate(Pitch = as.numeric(Pitch)) |> 
  na.omit()
```

```{r}
ggplot(data=results_cu,
       aes(x=Pitch, y=Difference)
  ) + geom_point() + geom_smooth(method = "lm", se=F) + facet_wrap(~role_key) +
  labs(title = "Cutter Velocity Average Difference", x="At-Bat", y="Difference in Velo from First Pitch")
```

```{r}
results_si <- pitches |>
  filter(pitch_type == "SI") |>
  group_by(pitch_type, game_date, player_name, role_key, pitcher_at_bat_number) |>
  summarize(mean_velo = mean(release_speed)) |>
  pivot_wider(names_from = pitcher_at_bat_number, names_sort = T, values_from = mean_velo) |>
  mutate(across(starts_with("2") : ends_with("35"), ~ . - `1`, .names = "{.col}")) |>
  group_by(player_name, role_key) |>
  summarize(across(c(4:37), mean, na.rm = TRUE)) |>
  pivot_longer(cols = c(3:36), names_to = "Pitch", values_to = "Difference") |>
  mutate(Pitch = as.numeric(Pitch)) |> 
  na.omit()
```

```{r}
ggplot(data=results_si,
       aes(x=Pitch, y=Difference)
  ) + geom_point() + geom_smooth(method = "lm", se=F) + facet_wrap(~role_key) +
  labs(title = "Sinker Velocity Average Difference", x="At-Bat", y="Difference in Velo from First Pitch")
```

```{r}
results |>
  filter(role_key == "SP") |>
  group_by(player_name, role_key) |>
  summarize(mean = mean(Difference)) |>
  arrange(mean)
```

```{r}
results_cu |>
  filter(role_key == "SP") |>
  group_by(player_name, role_key) |>
  summarize(mean = mean(Difference)) |>
  arrange(mean)
```

```{r}
results_si |>
  filter(role_key == "SP") |>
  group_by(player_name, role_key) |>
  summarize(mean = mean(Difference)) |>
  arrange(mean)
```

```{r}
results |>
  filter(role_key == "RP") |>
  group_by(player_name, role_key) |>
  summarize(mean = mean(Difference)) |>
  arrange(-mean)
```

```{r}
results_cu |>
  filter(role_key == "RP") |>
  group_by(player_name, role_key) |>
  summarize(mean = mean(Difference)) |>
  arrange(-mean)
```

```{r}
results_si |>
  filter(role_key == "RP") |>
  group_by(player_name, role_key) |>
  summarize(mean = mean(Difference)) |>
  arrange(-mean)
```

```{r}
plus_pitches <- szn |>
  replace(is.na(szn),0) |>
  filter(G > 15) |>
  select(4, 6, 9, 12, 97, 279, 282, 285, 288, 291, 294, 297, 300, 304) |>
  rename(
    "Changeup" = 6, 
    "Curveball" = 7, 
    "Fastball" = 8, 
    "Sinker" = 9, 
    "Slider" = 10, 
    "Knuckle_Curve" = 11, 
    "Cutter" = 12, 
    "Split_Finger" = 13, 
    "Forkball" = 14
    ) |>
  mutate(
    plus_pitches = rowSums(across(6:14, ~ . > 110, .names = "V{.col}")),
    ERA_dummy = ERA_minus < 100
    )

ggplot(data=plus_pitches,
    aes(x=plus_pitches, y=ERA_minus)
  ) + geom_smooth(method="lm") + facet_wrap(~Role) +
  labs(title = "ERA-minus vs Number of +Pitches",
       x="Number of Plus Pitches",
       y="ERA_minus")
```

```{r}
plus_pitches |>
  group_by(plus_pitches, Role, ERA_dummy) |>
  summarize(count = n()) |>
  ggplot(
       aes(x=plus_pitches, y=count, fill=ERA_dummy)) +
    geom_bar(stat="identity") + facet_wrap(~Role) +
  labs(title = "Pitchers with Above-Average ERA-minus",
       x= "Number of Plus Pitches",
       y= "Number of Pitchers",
       fill="ERA- < 100")
```

```{r}
plus_pitches |>
  filter(plus_pitches == 1, Role == "SP", Season == 2023, ERA_minus > 100)
```

```{r}
results |>
  filter(player_name == "Montero, Rafael") |>
  arrange(-Pitch)
```

```{r}
arsenal_p_rp |>
  filter(NameASCII == "Rafael Montero")

arsenal_gradesr |>
  filter(NameASCII == "Rafael Montero")
```

```{r}
szn |>
  replace(is.na(szn),0) |>
  filter(NameASCII == "Rafael Montero") |>
  select(4, 6, 9, 12, 97, 170, 174, 175, 179, 279, 285, 288, 291)
```

```{r}
pitches |>
  filter(player_name == "Strasburg, Stephen")
```

