---
title: "Report"
author: "Sebastian Kirkpatrick"
date: "2024-01-31"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

# Roles

For this exercise, I started with clustering to see what kind of role shows themselves in the data. When it comes to role, there are two core things that I want to look at. The leverage of the game situation a pitcher is put in, and the number of out that pitcher gets. For this, I created a new variable, outs per appearance, and used it in tandem with average game leverage index for my clustering. I expanded my number of clusters until two clusters were formed out of starters, then did one less. The resulting 7 clusters did not represent 7 different roles, but the clusters with a little bit of contrast helped cleared this up.

## Starters

This was a clear group, represented by one cluster. The difference between a front end and back end starter may be a differentiation in role. However, since that is more a result of team context, starter will be one role.

## Relievers

This is where we get some variation. The 6 non-cluster groups had all different kinds of pitchers and no one cluster was one role. After reviewing the clusters, three main groups appear.

### High Leverage, Single-Inning (SI) Relievers

These are the guys who pitch the late innings of the games. Mainly closers and setup men, this role comprised as few clusters. Almost every pitcher in this role average 3 out per innings. Their objective is to pitch a scoreless inning. 

### Long-Relievers

This group is more established based on their outs because they can come in at any times. In fact, most pitchers in this role did not come into games with high leverage. If you think about a long-reliever, that makes sense. They come in when the starter did not make it long enough to give the ball to the single-inning guys. This can be due to injury, or a blow-up start, which, either way, will often not result in a high leverage situation. There were some guys who pitch multiple, high-leverage innings, but they were more of an exception that the standard. The issue with perfectly separating these guys is that there are not very many, and, in the end, have the same general goal as starters: pitch as long as possible without giving up runs. Yes, their outs per game is normally between a single-inning workload and a starter, that is not always the case.

### The Rest of the Releivers

The final group is another group of single-inning guys, but with much less average leverage. These are the guys in the back of the bullpen who pitch when the games are not competitive. Some 6th-innings guys were placed here. While there was a clear difference in clusters between this group and the high-leverage arms, their outs per game were also around 3. Once again, this role is more explain by a the rest of a team's bullpen, so I will not really consider this group for the exercise of defining success. Success is exactly the same as high-leverage guys, just when the games don;t really matter.

# Characteristics of Success

While there are plenty of great estimators to use for future success, I will be using ERA for this exercise to describe success. At the end of the day, winning is about scoring more runs than the opponent and a successful pitcher does not give up runs. For the sake of adjusting for different ballparks and to be more clear in terms of the league average, I will look at a pitcher's ERA minus and see what other variables help (or do not help) explain why they kept runs off the board, or failed to do so.

## Pitch Arsenal

To start off, I looked at the percentage of the top 3 pitches for each pitcher and ran their correlation to ERA minus. For starters, both primary % and secondary % have negative correlations, though for Primary, it is near zero. The correlation is positive for the third pitch. This makes sense as the more a starter throws their third pitch should help them out. For single-inning arms, only the correlation with Primary was negative. This follows along with the trend that two-pitch pitchers can be more successful as relievers. Plus, guys who only rely on one pitch are not normally as successful. Finally, the correlations for multi-inning arms were all positive, except for correlation with the third pitch. This is does not exactly conform with the role, but may be due to the small number of guys who average more than 4 outs per inning.

## Pitch Stuff+ Grades

The next step was to do the same correlations, but instead of using the percent of the pitches, using the grades of stuff+ for those pitches. Unsurprisingly, the correlations with ERA minus were all negative and were strongest for Primary, then secondary, and finally the third offering for starters. Thus, the starters with the most success have highly graded pitches for their top three offerings. Also, a strong primary pitch is crucial for a starter. For single-inning relievers, there are all negative, but have much less correlation than starters. The correlation between the primary for SI arms is about the same as the correlation for the secondary of starters. The stuff+ is less correlated across the board for relievers, but it is clear that primary and secondary are much more correlated to ERA minus than the third offering. Finally, for long relievers, they are all negative, but all very close to each other. They are the least correlated for primary and secondary, but have a third pitch more correlated than SI arms. AT least in terms of correlations, it seems the more a pitcher has to pitch, the more correlated a third offering becomes with ERA minus. 

## Regression Analysis

The next step I took was performing linear regression with ERA minus as the response and the grade of the top 3 used pitches as the inputs. For each role, I found which variables were, and more importantly, were not, significant in creating a model to predict ERA minus. For starters, all three grades were statistically significant and all three had negative coefficients with primary the most negative, then secondary, and finally the third pitch. The model SI Relievers held the Stuff+ of the third pitch not significant. The coefficient were still both negative and primary was more negative than secondary. Finally, long relievers only had primary as the only significant predictor. 

## Evaluation of Plus-Pitches

Before getting to the analysis of plus pitches, it is important to note that I have decided the role of long reliever is not going to be considered here. The linear model was almost not significant at all, so I kept those players in the analysis, but focused on their role of whether or not they started a game for this section. 

With that being said, I found the trend line of plus pitches (pitches with stuff plus greater than one standard deviation of the mean) vs ERA minus. The difference is that the slops i much steeper for starters, which explains why a third pitch is more important for starters than relievers. However, the general shape of the lines are similar, which is important. Having multiple plus pitches sets a pitcher up for success regardless of role. Looking at the count of above average pitchers, the proportion of above average pitchers at each level of plus pitches is about the same for starter and relievers, confirming this idea. So, there needs to be something else, not just plus pitches that can set a starter apart.

## wOBA Across an Outing

This is where I start to define characteristics for someone potentially changing roles. Yes, these are also characteristics of success, but will also aid in finding who could change roles. For a starter, or a long reliever, it is clear that they need to pitch more. Outside of arm durability, they also need to still be successful for more pitches. Just between Sp and RP, I found the mean wOBA of each pitch for every pitch thrown. The graph shows a clear trend: reliever are better at minimizing wOBA until about pitch 25. Then, their mean wOBA skyrockets. Starters, while starting higher than relievers, stay pretty stable up to 100 pitches. 

## Average Velocity Drop

We need our starters to be consistent for much longer periods of time, and the place I looked was fastball velocity. I took the pitch data for four-seams, cutters, and sinkers and graphed the average dip from the first at-bat for each pitcher. Then, by separating SP and RP, a clear drop happens. Velocity for all of thew pitches decrease much sharper for relievers compared to starters. For a successful starter, we need their fastball, or whatever primary speed pitch they use, to be consistent.

# Candidates for New Roles



## Candidate 1: RP -> SP/LR



## Candidate 2: SP -> SIR

